apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejsapp
  name: nodejsapp-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: nodejsapp
status:
  loadBalancer: {}