FROM ubuntu:20.04

RUN apt-get update; \
	apt-get install -y wget 

RUN wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
	dpkg -i packages-microsoft-prod.deb && \
	rm packages-microsoft-prod.deb

#RUN apt-get update; \
#	apt-get install -y apt-transport-https && \
#	apt-get update && \
#	apt-get install -y dotnet-sdk-6.0


RUN apt update && \
	apt install -y apt-transport-https dotnet-sdk-6.0


RUN dotnet tool install --tool-path /tools dotnet-trace && \
	dotnet tool install --tool-path /tools dotnet-counters && \
	dotnet tool install --tool-path /tools dotnet-dump && \
	dotnet tool install --tool-path /tools dotnet-sos

ENTRYPOINT ["/bin/sh"]