apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret-store-csi-mount-env-var
spec:
  provider: azure
  parameters:
    keyvaultName: "kv-secret-store-csi-001" # the name of the KeyVault
    tenantId: "328214bc-e88f-43fb-bad1-8f64ff51d823" # the tenant ID of the KeyVault
    objects: |
      array:
        - |
          objectName: mysupersecret
          objectAlias: mysupersecretalias      # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret              # object types: secret, key or cert. For Key Vault certificates, refer to https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys/ for the object type to use
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty

  secretObjects: # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
    - secretName: secret-created-automatically # name of the Kubernetes secret object
      type: Opaque # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
      data:
        - key: mysupersecret # data field to populate
          objectName: mysupersecretalias # this could be the object name or the object alias

